type c = i32;

enum quoteType {
    EQUITY,
    
}

struct QueryResponse {
	quoteType : c, //enum ,
	quoteSourceName : String ,
	currency : c, //enum
	marketState : c ,//enum ,
	regularMarketChangePercent : u64 ,
	regularMarketPrice : u64 ,
	exchange : String ,
	shortName : String ,
	longName : String ,
	exchangeTimezoneName : String ,
	exchangeTimezoneShortName : String ,
	gmtOffSetMilliseconds : f64 ,
	market : String ,
	esgPopulated : bool ,
	hasPrePostMarketData : bool ,
	firstTradeDateMilliseconds : f64 ,
	priceHint : i32 ,
	postMarketChangePercent : f64 ,
	postMarketTime : u64 ,
	postMarketPrice : f64 ,
	postMarketChange : f64 ,
	regularMarketChange : f64 ,
	regularMarketTime : u64 ,
	regularMarketDayHigh : f64 ,
	regularMarketDayRange : String ,
	regularMarketDayLow : f64 ,
	regularMarketVolume : f64 ,
	regularMarketPreviousClose : f64 ,
	bid : f64 ,
	ask : f64 ,
	bidSize : f64 ,
	askSize : f64 ,
	fullExchangeName : String ,
	financialCurrency : c, //enum
	regularMarketOpen : u64, //timestamp
	averageDailyVolume3Month : u64 ,
	averageDailyVolume10Day : u64 ,
	fiftyTwoWeekLowChange : f64 ,
	fiftyTwoWeekLowChangePercent : f64 ,
	fiftyTwoWeekRange : String ,
	fiftyTwoWeekHighChange : f64 ,
	fiftyTwoWeekHighChangePercent : f64,
	fiftyTwoWeekLow : f64 ,
	fiftyTwoWeekHigh : f64 ,
	fiftyTwoWeekChangePercent : f64 ,
	earningsTimestamp : u64 ,
	earningsTimestampStart : u64 ,
	earningsTimestampEnd : u64 ,
	trailingAnnualDividendRate : f64 ,
	trailingPE : f64 ,
	trailingAnnualDividendYield : f64 ,
	epsTrailingTwelveMonths : f64 ,
	epsForward : f64 ,
	epsCurrentYear : f64 ,
	priceEpsCurrentYear : f64 ,
	sharesOutstanding : i64 ,
	bookValue : f64 ,
	fiftyDayAverage : f64 ,
	fiftyDayAverageChange : f64 ,
	fiftyDayAverageChangePercent : f64 ,
	twoHundredDayAverage : f64,
	twoHundredDayAverageChange : f64 ,
	twoHundredDayAverageChangePercent : f64 ,
	marketCap : f64 ,
	forwardPE : f64 ,
	priceToBook : f64 ,
	sourceInterval : f64 ,
	exchangeDataDelayedBy : f64 ,
	averageAnalystRating : cString,
	displayName : String ,
	symbol : String ,
    json : String, //contains the entire listed information above
}

//list enums below yasss queen
